version: "3.7"

networks:
  host:
    external: true
    name: host

volumes:
  avahicfg:
    name: avahicfg
    driver: local
    driver_opts:
      type: none
      device: ./avahi
      o: bind,ro
  sambacfg:
    name: sambacfg
    driver: local
    driver_opts:
      type: none
      device: ./samba
      o: bind,ro
  sambadb:
    name: sambadb
    driver: local
    driver_opts:
      type: none
      device: ./sambalib
      o: bind
  storage:
    name: storage
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

services:
  samba:
    image: fat0troll/samba-with-avahi:latest
    env_file:
      - ./env
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - host
    tty: true
    volumes:
      - type: volume
        source: storage
        target: /data
      - type: volume
        source: avahicfg
        target: /etc/avahi
      - type: volume
        source: sambacfg
        target: /etc/samba
      - type: volume
        source: sambadb
        target: /var/lib/samba
